name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  autotests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Run Tests in Docker
        run: docker run -v ./:/tests ghcr.io/mazon7/mytests
